### PR TITLE
Sub events now send channel in the 'Extra' data

### PR DESCRIPTION
**Pull request by MichaelJolley**
It looks like sub events (sub, subgift, resub, submysterygift) weren't sending along the channel parameter like other events. Added that property and updated types to reflect the new property.

### CODE REVIEW

**Comment by instafluff** [comment]
THANK YOU!!!!

**Comment by MichaelJolley** [comment]
Thank you for the project! Can we get a release sometime? I have a project that's awaiting these changes for its release. 🥰

**Comment by instafluff** [comment]
Just finished setting up GitHub actions today for this so there's a new published version now!
-------- Original message --------From: Michael Jolley ***@***.***> Date: 3/20/21  6:55 PM  (GMT-08:00) To: instafluff/ComfyJS ***@***.***> Cc: Instafluff ***@***.***>, State change ***@***.***> Subject: Re: [instafluff/ComfyJS] Sub events now send channel in the 'Extra' data (#30) 

Thank you for the project! Can we get a release sometime? I have a project that's awaiting these changes for its release. 🥰

**Comment by MichaelJolley** [comment]
Sweet. I was literally thinking about tackling that next. Well done and thanks!

**Pull request merged**
