### PR TITLE
Added more event to listen to and client accessor

### PR DESCRIPTION
**Pull request by talk2MeGooseman**
Added more event handlers for things I would like to listen to for a future project I am going to work on. @AlcaDesign also added a GetClient accessor method in case a developer wants to hook into more tmi.js/Twitch events.

Brought to you with love and pair programming by:
talk2megooseman
@AlcaDesign

### CODE REVIEW

**Comment by instafluff** [comment]
Awesome!! Would you mind updating it to use `extra` with more specific properties than just userstate like e572e46eb213de1083246a2b4e1f846c5acb25ff and changing from `username` to `user` for consistency?

**Comment by talk2MeGooseman** [comment]
Will do 👍

**Comment by talk2MeGooseman** [comment]
Added in extra metadata where its applicable for events, thanks for the feedback 😃

**Comment by instafluff** [comment]
Looks great!

**Pull request merged**
